### ISSUE TITLE
Lỗi chức năng ref, thêm chức năng

### ISSUE THREAD

**Issue by HoanDao** [zuydd/gpm-get-user#1]
Lỗi chức năng tự động ref bác ạ. Con moonbix e để lên 6s chờ rồi mà nó vẫn không nhận. bác có thể thêm chức năng chọn cách lấy dữ liệu không. con thì lấy  query_id , con thì lấy user, con thì lấy auth

**Comment by shakeblue** [comment]
![image](https://github.com/user-attachments/assets/3262b0ef-bcc2-43f8-a1ea-4af128c369d9)
Máy mình bị stuck ở đoạn ghi ra excel bạn có biết nguyên nhân là gì ko ạ?

**Comment by zuydd** [comment]
> Lỗi chức năng tự động ref bác ạ. Con moonbix e để lên 6s chờ rồi mà nó vẫn không nhận. bác có thể thêm chức năng chọn cách lấy dữ liệu không. con thì lấy query_id , con thì lấy user, con thì lấy auth

bạn check lại xem đã lấy đúng id ref chưa nhé, con này nó sẽ load iframe và call 1 API để nghi nhận ref. Mà vấn đề giờ là bypass kiểu gì thôi :))))

**Comment by zuydd** [comment]
> ![image](https://private-user-images.githubusercontent.com/19905946/370825627-3262b0ef-bcc2-43f8-a1ea-4af128c369d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDU5NjAsIm5iZiI6MTcyNzM0NTY2MCwicGF0aCI6Ii8xOTkwNTk0Ni8zNzA4MjU2MjctMzI2MmIwZWYtYmNjMi00M2Y4LWExZWEtNGFmMTI4YzM2OWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDEwMTQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiZTllNTY4ZjExZDA2MTRmOWU2NzQ3YjMzNzViYjU4MWE4NTYzZDZlMDFlNDU0NWFjZTFmMWVkZjJkZTk5NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.U9Eoha5ELiEh7pporORODX7S3itNzLr904Pq58MxS6E) Máy mình bị stuck ở đoạn ghi ra excel bạn có biết nguyên nhân là gì ko ạ?

bạn kiểm tra xem có đang mở file excel nào không, sâu hơn có thể xem lại user cài GPM có quyền ghi file ko, lỗi này là cố hữu với GPM xưa giờ rồi, chứ ko phải do script

**Comment by HoanDao** [comment]
Làm sao để thêm Bot vậy bác. E chạy cho con bot BybitCoinsweeper_Bot không ra. Hướng dẫn e thêm nó vào được ko

**Comment by zuydd** [comment]
> Làm sao để thêm Bot vậy bác. E chạy cho con bot BybitCoinsweeper_Bot không ra. Hướng dẫn e thêm nó vào được ko

Bot chỉ có mình thêm được thôi, cần con nào thì ib tele mình, riêng con BybitCoinsweeper_Bot thì chịu do game nó ko có cơ chế mở bằng lệnh

**Comment by HoanDao** [comment]
Con seed_coin_bot cũng không lấy được bác ạ.

**Comment by zuydd** [comment]
ib tele mình nhé, chứ github 3-4 ngày mình mới check issue 1 lần dễ miss
